#!/usr/bin/env bash
# Script name: fzr
# Written by fullsalvo
# Depends on https://github.com/junegunn/fzf
# Lists usable rhisk themes and allows selection via \t (tab)

# Function

fzr () {
	local themes
	mapfile -t themes < <(rhisk -c | sort -d | fzf --multi --reverse --cycle)
	(( ${#themes[@]} > 0 )) && rhisk "${themes[@]}"
}

fzr
