#!/usr/bin/env bash
# Script Name: reload-desktop
# Written by fullsalvo
# Contains the commands to restart programs after whizkers makes changes

reload_config=~/.rhisk

declare usefont=0
declare tmux_conf=~/.tmux.conf
declare xres=~/.Xresources

# Functions

use-xresources ()
{
	tr -d ' \t' | sed -n '
s/.*background:/\x1b]11;/p
s/.*foreground:/\x1b]10;/p
s/.*cursorColor:/\x1b]12;/p
s/.*borderColor:/\x1b]708;/p
s/.*color\([0-9][^:]*\):/\x1b]4;\1;/p
' | tr \\n \\a
}

use-xresourcesfont ()
{
    tr -d ' \t' | sed -n '
s/URxvt.font:/\x1b]50;/p
s/.*background:/\x1b]11;/p
s/.*foreground:/\x1b]10;/p
s/.*cursorColor:/\x1b]12;/p
s/.*borderColor:/\x1b]708;/p
s/.*color\([0-9][^:]*\):/\x1b]4;\1;/p
' | tr \\n \\a
}

getwm ()
{
    if [ -n "$DISPLAY" ]; then
	id="$(xprop -root -notype | \awk '$1=="_NET_SUPPORTING_WM_CHECK:"{print $5}')"
	wm="$(xprop -id "$id" -notype -f _NET_WM_NAME 8t)"
	wm="${wm/*_NET_WM_NAME = }"
	wm="${wm/\"}"
	wm="${wm/\"*}"
    fi
}

# Main

main ()
{
	# Read config file
	[ -f "$reload_config" ] && source "$reload_config"

	# Programs that require a keypress to reload configs
	n=0
	for prog in "${reload_key_programs[@]}"; do
		for window in `xdotool search --class $prog`; do
 			xdotool key --window $window ${reload_keypresses[n]} &>/dev/null &
		done
		n=n+1
	done

	# Programs
	# User-specified programs
	for prog in "${reload_programs[@]}"; do
		killall "${prog%% *}"
		$prog &>/dev/null &
	done &

	# Commands
	for com in "${reload_commands[@]}"; do
		$com &>/dev/null &
	done

	# Reload X terminal emulator configuration live
	if [[ -n $xres ]]; then
		xrdb "$xres" &>/dev/null &
		if [ $usefont -eq 0 ]; then
			for pts in /dev/pts/*; do
				(echo -n "$(use-xresources < "$xres")" > "$pts") 2>/dev/null &
			done &
		else
			for pts in /dev/pts/*; do
				(echo -n "$(use-xresourcesfont < "$xres")" > "$pts") 2>/dev/null &
			done &
		fi
	fi

	# Reload termite, if the user has it
	# (I assume that if you have termite, you use it)
	if [[ -n $(pgrep termite) ]]; then
		killall -s USR1 termite &>/dev/null &
	fi

	# Reload cava
	if [[ -n $(pgrep cava) ]]; then
		killall -s USR1 cava &>/dev/null &
	fi

	# Window Manager {{{
	# Reload window manager
	getwm
	case "$wm" in
		i3)
			i3-msg 'restart' &>/dev/null &
			;;
		Openbox)
			openbox --reconfigure &>/dev/null &
			;;
		Awesome)
			echo 'awesome.restart()' | awesome-client &>/dev/null &
			;;
		herbstluftw)
			herbstclient reload &>/dev/null &
			;;
	esac

	# Tint2
	if [[ -n $(pgrep tint2) ]]; then
		killall -s USR1 tint2 &>/dev/null &
	fi

	# tmux
	# Reload tmux colors
	if [[ -n "$tmux_conf" ]]; then
		tmux source-file "$tmux_conf" &>/dev/null &
	fi
}

main
